docs/Django/lottostar/apps/blog/urls.py
from django.conf.urls import *
from apps.blog import views

urlpatterns = patterns('apps.blog.views',
    url(r'^admin/translate/post/(?P<post_id>[a-zA-Z0-9_.-]+)/$', "admin_post_text", name="admin_post_text"),
    url(r'^admin/translate/category/(?P<category_id>[a-zA-Z0-9_.-]+)/$', "admin_category_text", name="admin_category_text"),
    url(r'^admin/translate/tag/(?P<tag_id>[a-zA-Z0-9_.-]+)/$', "admin_tag_text", name="admin_tag_text"),

    url('^$', views.PostListView.as_view(), name='blog'),
    url('^category/(?P<slug>[a-zA-Z0-9_.-]+)/$', views.CategoryListView.as_view(), name='blog_category'),
    url('^tag/(?P<slug>[a-zA-Z0-9_.-]+)/$', views.TagListView.as_view(), name='blog_tag'),
    url('^(?P<slug>[a-zA-Z0-9_.-]+)/comment/$', views.PostCommentCreateView.as_view(), name='blog_comment_post'),
    url('^(?P<year>[a-zA-Z0-9_.-]+)/(?P<month>[a-zA-Z0-9_.-]+)/$', views.MonthListView.as_view(), name='blog_month'),
    url('^(?P<slug>[a-zA-Z0-9_.-]+)/$', views.PostDetailView.as_view(), name='blog_post'),
)

docs/Django/lottostar/apps/game/urls.py
from django.conf.urls import *
from apps.game import views

urlpatterns = patterns('',
    url(r'^admin/game/overview/$', views.GameOverView.as_view(), name='admin_game_overview'),
    url('^results/$', views.GameResultsList.as_view(), name='game_results'),
    url('^results/(?P<slug>[a-zA-Z0-9_.-]+)/$', views.GameResultsGameList.as_view(), name='game_results_game'),
    url(r'^game/draw-result/$', views.draw_result_view, name='draw_result'),
)

docs/Django/lottostar/local/urls.py
/home/gutembert/src/lottostar/urls.py

docs/Django/lottostar/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^',                       include('trans.urls')),
    #url(r'^',                       include('surveys.urls')),

    url(r'^admin/',                 include(admin.site.urls)),
    url(r'^admin/doc/',             include('django.contrib.admindocs.urls')),
    url(r'^admin/',                 include(admin.site.urls)),

    url(r'^admin_tools/',           include('admin_tools.urls')),
    url(r'^admin/filebrowser/',     include('filebrowser.urls')),
    url(r'^media/tinymce/',         include('tinymce.urls')),

    url(r'^faq/',                   include('faq.urls')),
    url(r'^blog/',                  include('blog.urls')),
    url(r'^',                       include('game.urls')),
    url(r'^',                       include('play.urls')),
    url(r'^',                       include('account.urls')),
    url(r'^',                       include('pages.urls')),
    url(r'^',                       include('system.urls')),
    url(r'^promotions/',            include('promotions.urls')),
    url(r'^',                       include('mobile.urls')),
    url(r'^test/',                  include('devtest.urls')),
    url(r'^',                       include('surveys.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(.*)$',            'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/static/' }),
        (r'^sites/(.*)$',             'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/sites/' }),
        (r'^admin_tools/(.*)$',       'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/static/admin_tools/'}),
        (r'^robots.txt$',             'django.views.static.serve', {'path' : "/static/robots.txt", 'document_root': settings.PROJECT_ROOT, 'show_indexes': False }),
        (r'^favicon.ico/$',           'django.views.static.serve', {'path' : "/static/favicon.ico", 'document_root': settings.PROJECT_ROOT, 'show_indexes': False }),
        (r'^media/(.*)$',             'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/media/' }),
    )

docs/Django/lottostar/apps/game/models.py
import datetime
from django.contrib.sites.models import Site
from django.db import models
from django.utils.translation import ugettext_lazy as _
from djorm_expressions.models import ExpressionManager
from djorm_pgarray.fields import ArrayField
from json_field import JSONField

class Product(models.Model):
    site = models.ManyToManyField(Site, blank=True, null=True)
    STATUS_CHOICES = (
        ("pending",      _("Pending")),
        ("active",       _("Active")),
        ("disabled",     _("Disabled")),
        ("deleted",     _("Deleted")),
    )

    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    status = models.CharField(max_length=255, choices=STATUS_CHOICES)

    cost = models.FloatField(default=0, blank=True) # for reporting
    price = models.FloatField(default=0, blank=True) # for reporting

    description = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __unicode__(self):
        return self.name

    def get_current_winning(self):
        return Event.objects.filter(game=self.get_game(), draw_datetime__lte=datetime.datetime.today()).order_by("-draw_datetime")[:1].get()

    def get_jackpot(self):
        return self.productgame_set.all()[:1].get().game.jackpot

    def get_game(self):
        return self.productgame_set.all()[:1].get().game

    def get_product_game(self):
        return self.productgame_set.all()[:1].get()

    def get_game_price(self):
        return self.productgame_set.all()[:1].get().game.price

    def get_remaining_time(self):
        #s = (self.productgame_set.all()[:1].get().game.next_draw_date().draw_datetime - datetime.datetime.now()).seconds
        s = self.productgame_set.all()[:1].get().game.next_draw_date().draw_datetime - datetime.datetime.now()
        days, remainder = divmod(s.total_seconds(), 86400)
        hours, remainder = divmod(remainder, 3600)
        minutes, seconds = divmod(remainder, 60)
        return '%02d:%02d:%02d' % (days, hours, minutes)

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"


class Game(models.Model):
    GAME_TYPE_CHOICES = (
        ("lottery", _("Lottery")),
    )
    STATUS_CHOICES = (
        ("pending",      _("Pending")),
        ("active",       _("Active")),
        ("disabled",     _("Disabled")),
    )

    game = models.ForeignKey("self", related_name="games", blank=True, null=True)

    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True, null=True)

    active = models.BooleanField(default=True, blank=True)
    status = models.CharField(max_length=255, choices=STATUS_CHOICES)
    game_type = models.CharField(max_length=255, choices=GAME_TYPE_CHOICES, default="lottery") # exclude from admin

    exclude_selection = models.BooleanField(default=False, blank=True)

    description = models.TextField(blank=True, null=True)

    jackpot = models.FloatField(default=0)
    rollover = models.IntegerField(default=0, null=True, blank=True)

    multiplier_price = models.FloatField(default=0, null=True, blank=True)

    cost = models.FloatField(default=0)
    price = models.FloatField(default=0, null=True, blank=True)
    points = models.FloatField(default=0, null=True, blank=True) #todo: user has points

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __unicode__(self):
        return self.name

    def get_events(self):
        return Event.objects.filter(game=self, draw_datetime__gte=datetime.datetime.today()).order_by("draw_datetime")

    def current_draw(self):
        try:
            return Event.objects.filter(game_id=self.id, draw_datetime__lte=datetime.datetime.now(), game_status="complete").order_by('-draw_datetime')[0]
        except :
            return None

    def next_draw_date(self):
        return Event.objects.filter(draw_datetime__gt=datetime.datetime.now(), game_id=self.id).order_by("draw_datetime")[0]

    #get last draw date

    class Meta:
        verbose_name = "Game"
        verbose_name_plural = "Games"
        ordering = ["-name"]


class Event(models.Model):
    GAME_STATUS_CHOICES = (
        ("open",        _("Open")),
        ("closed",      _("Closed")),
        ("cancelled",   _("Cancelled")),
        ("paused",      _("Paused")),
        ("complete",    _("Complete")),
    )
    PROGRESS_CHOICES = (
        ("pending",        _("Pending")),
        ("results",        _("Results")),
        ("winnings",       _("Winnings")),
        ("notification",   _("Notification")),
        ("complete",       _("Complete")),
    )
    game = models.ForeignKey(Game)

    game_status = models.CharField(max_length=255, choices=GAME_STATUS_CHOICES)
    progress = models.CharField(max_length=255, choices=PROGRESS_CHOICES)

    draw_datetime = models.DateTimeField()
    cutoff = models.DateTimeField()

    rollover = models.IntegerField(default=0, null=True, blank=True)

    has_event_result_entry = models.BooleanField(default=False, blank=True)
    has_event_result_winner = models.BooleanField(default=False, blank=True)

    processed_results = models.BooleanField(default=False, blank=True)
    processed_winnings = models.BooleanField(default=False, blank=True)

    jackpot = models.FloatField(default=0)
    payout = models.FloatField(default=0)

    balls1 = ArrayField(dbtype="int", null=True, blank=True)
    balls2 = ArrayField(dbtype="int", null=True, blank=True)
    balls3 = ArrayField(dbtype="int", null=True, blank=True)

    entries = models.IntegerField(max_length=11) # for reporting

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = ExpressionManager()

    def __unicode__(self):
        return self.draw_datetime.strftime("%d/%m/%Y")

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"

class Ballset(models.Model):
    game = models.ForeignKey(Game)
    name = models.CharField(max_length=255)
    main = models.IntegerField()
    bonus = models.IntegerField()
    ball_min = models.IntegerField()
    ball_max = models.IntegerField()
    wheeling_limit = models.IntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        verbose_name = "Ballset"
        verbose_name_plural = "Ballsets"


class GamePrize(models.Model):
    PRIZE_TYPE_CHOICES = (
        ("jackpot",     _("Jackpot")),
        ("cash",        _("Cash")),
        ("credit",      _("Credit")),
        ("voucher",     _("Voucher")),
        ("multiplier",  _("Multiplier")),
        ("discount",    _("Discount")),
    )

    game = models.ForeignKey(Game)
    prize_type = models.CharField(max_length=255, choices=PRIZE_TYPE_CHOICES, default="cash") #exclude from admin
    tier = models.IntegerField(max_length=3)

    name = models.CharField(max_length=255)
    value = models.FloatField(default=0)

    main_balls = ArrayField(dbtype="int", null=True, blank=True)
    bonus_balls = ArrayField(dbtype="int", null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "Prize"
        verbose_name_plural = "Prizes"
        ordering = ["tier"]


class EventPrize(models.Model):
    PRIZE_TYPE_CHOICES = (
        ("jackpot",     _("Jackpot")),
        ("cash",        _("Cash")),
        ("credit",      _("Credit")),
        ("voucher",     _("Voucher")),
        ("multiplier",  _("Multiplier")),
        ("discount",    _("Discount")),
    )
    event = models.ForeignKey(Event)
    prize_type = models.CharField(max_length=255, choices=PRIZE_TYPE_CHOICES)
    tier = models.IntegerField(max_length=3)
    name = models.CharField(max_length=255)
    value = models.FloatField(default=0)

    winners = models.IntegerField(null=True, blank=True)
    matching_ballset = JSONField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["tier"]
        verbose_name = "Prize"
        verbose_name_plural = "Prizes"



class EventRule(models.Model):
    SCHEDULE_CHOICES = (
        ("once",    _("Once")),
        ("weekly",  _("Weekly")),
        ("monthly", _("Monthly")),
        ("yearly",  _("Yearly")),
    )

    game = models.ForeignKey(Game)
    schedule = models.CharField(max_length=255, choices=SCHEDULE_CHOICES)
    params = JSONField(blank=True, null=True)
    cutoff = models.IntegerField(max_length=3)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        verbose_name = "Event Rule"
        verbose_name_plural = "Event Rules"

    def __unicode__(self):
        return "%s %s"  % (self.game.name, self.schedule)

#*
class ProductGame(models.Model):
    product = models.ForeignKey(Product)
    game = models.ForeignKey(Game)
    discount = models.FloatField(default=0, blank=True)
    allow_addons = models.BooleanField(default=True, blank=True)
    allow_addons_discount = models.BooleanField(default=True, blank=True)

    consecutive = models.BooleanField(default=False, blank=True)
    entries = models.IntegerField(default=0, blank=True)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __unicode__(self):
        return "%s - %s" % (self.product.name , self.product.name)


class ProductGameBoost(models.Model):
    product_game = models.ForeignKey(ProductGame)

    name = models.CharField(max_length=50)

docs/Django/lottostar/apps/game/views.py
import datetime
from django.core.cache import cache
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.views.decorators.csrf import csrf_exempt, requires_csrf_token
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from apps.game.models import Game, GameDrawResult, Event, Product
from play.models import Entry
from settings import CACHE_TIME
from play.forms.game import GameOverviewForm


class FormListView(FormMixin, ListView):
    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        self.form = self.get_form(form_class)

        self.object_list = self.get_queryset()
        context = self.get_context_data(object_list=self.object_list, form=self.form)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)


class GameOverView(FormListView):
    form_class = GameOverviewForm
    model = Game
    template_name = 'admin/games/game_overview.html'

    def get_context_data(self, **kwargs):
        context = super(GameOverView, self).get_context_data(**kwargs)
        game_ids = [] #default game ids

        products = Product.objects.filter(status="active")
        for product in products:
            game_ids.append(product.id)

        games=context['form']['games'].value()
        if games is not None and len(games) > 0:
            game_ids = games

        products = products.filter(id__in=game_ids)

        start_date=datetime.datetime.now()
        from_date=context['form']['from_date'].value()
        if from_date and from_date is not None:
            start_date = datetime.datetime.strptime(from_date, '%d-%m-%Y').strftime('%Y-%m-%d 00:00:00')

        end_date=datetime.datetime.now() + datetime.timedelta(weeks=1)
        to_date=context['form']['to_date'].value()
        if to_date and to_date is not None:
            end_date=datetime.datetime.strptime(to_date, '%d-%m-%Y').strftime('%Y-%m-%d 23:59:59')

        event_list = Event.objects.filter(
            draw_datetime__gte = start_date,
            draw_datetime__lte = end_date,
            game_id__in = game_ids
        ).order_by("draw_datetime")

        context["dates_list"] = Entry.objects.filter(event__in = event_list).select_related("draw_datetime", "ticket", "ticket__product", "ticket__transaction", "event")
        context["product_list"] = products

        return context


class GameResultsList(ListView):
    model = Product
    template_name = "game/results_list.html"
    context_object_name = "product_list"


class GameResultsGameList(DetailView):
    model = Product
    template_name = "game/results_detail.html"

    def get_context_data(self, **kwargs):
        context = super(GameResultsGameList, self).get_context_data(**kwargs)
        game = self.get_object().get_game()
        game_list = Event.objects.filter(game=game, draw_datetime__lte=datetime.datetime.today()).order_by("-draw_datetime")
        context["game_list"] = game_list
        context["lottery_draw"] = game_list[0]
        return context


def draw_result_view(request):
    context = {}
    product = Product.objects.get(slug=request.GET['product_slug'])
    context["lottery_draw"] = Event.objects.get(id=int(request.GET['event_id']))
    context["product"] = product
    context["game"] = product.get_game()
    return render_to_response('game/draw_results.html', context, context_instance=RequestContext(request))

docs/Django/lottostar/apps/game/templates/game/draw_results.html
{% load game_tag_helpers i18n %}

<div>
    <table>
        <thead>
            <tr>
                <td colspan="2" width="960">
                    <div class="row">
                        <div class="small-4 columns">
                            <img src="/static/img/games/{{ product.slug }}/img/logo-long.png" style="max-height: 60px">
                        </div>
                        <div class="small-7 columns">
                            <h2 class="text-right" style="margin: 5px 0px 0px"><small> {{ product.draw_datetime|date:"l, d M Y" }}</small></h2>
                            <a href="{% url "game" product.slug %}"><button class="button radius right">{% trans "Play Now" %}</button></a>
                        </div>
                    </div>

                </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td id="draw_entries_{{ product.slug }}" width="500">
                    <h3>{% trans "Winning numbers" %}</h3>
                    {% display_game_winning_numbers lottery_draw.balls1 lottery_draw.balls2 %}
                </td>
                <td id="draw_entries_{{ product.slug }}">
                    <hgroup>
                        <h3>{% trans "Jackpot" %}</h3>
                        <h2>{{ lottery_draw.jackpot|currency|safe }}</h2>
                    </hgroup>
                </td>
            </tr>
        </tbody>
    </table>

    <h4>{{ game }}</h4>
    <table>
        <tr>
            <th width="505">{% trans "Results" %}</th>
            <th width="450">{% trans "Prize per winner" %}</th>
        </tr>
        {% for prize in product.get_game.gameprize_set.all %}
        <tr>
            <td>{{ prize.name }}</td>
            <td>&euro; {% get_draw_prize lottery_draw.id prize.id %}</td>
        </tr>
        {% endfor %}
    </table>

    {% if product.get_game.games.get %}
        {% display_game_bonus lottery_draw.balls2 lottery_draw.balls3 %} <h4>{{ product.get_game.games.get }}</h4>
        <table>
            <tr>
                <th width="505">{% trans "Results" %}</th>
                <th width="450">{% trans "Prize per winner" %}</th>
            </tr>
            {% for prize in product.get_game.games.get.gameprize_set.all %}
            <tr>
                <td>{{ prize.name }}</td>
                <td>&euro; {% get_draw_prize lottery_draw.id prize.id %}</td>
            </tr>
            {% endfor %}
        </table>
    {% endif %}
</div>

docs/Django/lottostar/apps/game/templates/game/previous_draw_dates.html
{% load humanize game_tag_helpers %}
<select style="width: 300px" name="event-date" id="event_date" onchange="getDrawResult(true); ">
    {% for event in game|get_query_set  %}
        <option value="{{ event.id }}">{{ event.draw_datetime|date:"d M Y (l)" }}</option>
    {% endfor %}
</select>

docs/Django/lottostar/apps/game/templates/game/results_detail.html
{% extends "base.html" %}
{% load thumbnail i18n  game_tag_helpers %}

{% block js %}
    <script type="text/javascript">
        var product_slug = "{{ product.slug }}";
    </script>
    <script src="/static/js/results.js"></script>
{% endblock %}

{% block content %}
    <section id="content" class="row">
        <div class="main-panel">
            <ul class="breadcrumbs">
                <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
                <li><a href="{% url "game_results" %}">{% trans "Results" %}</a></li>
                <li class="current"><a href=".">{% trans "RESULTS AND WINNING NUMBERS" %}</a></li>
            </ul>

            <h1>{{ product.name|upper }} {% trans "LOTTERY RESULTS" %}</h1>

            <div>
                <div class="small-3 left">{% trans "Choose a Date" %}</div>
                <div class="small-5 left">
                    <select name="game_event" id="game_event">
                        {% for date in game_list %}
                            <option value="{{ date.id }}">{{ date.draw_datetime|date:"l, d M Y" }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <br/> &nbsp;
            <br/>

            <div id="resultloader">
                <br/>
                <br/>
                <br/>
                <center>
                    <img src="/static/img/loading.gif" alt="" width="128" height="128" /> <br/>
                    <h2>{% trans "Loading" %}...</h2>
                </center>
                <br/>
                <br/>
                <br/>
            </div>

            <div id="game_draw_results">
                {% include "game/draw_results.html" %}
            </div>

        </div>
        {% include "partials/sidebar.html" %}
    </section>
{% endblock %}

docs/Django/lottostar/apps/game/templates/game/results_list.html
{% extends "base.html" %}
{% load thumbnail i18n humanize game_tag_helpers %}

{% block content %}
    <section id="content" class="row">
        <div class="main-panel">
            <ul class="breadcrumbs">
                <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
                <li class="current"><a href=".">{% trans "RESULTS AND WINNING NUMBERS" %}</a></li>
            </ul>
            <h1>{% trans "CURRENT LOTTERY RESULTS" %}</h1>
            <div class="results">
                {% for product in product_list %}
                <table>
                    <thead>
                        <tr>
                            <td colspan="2" width="960">
                                <div class="row">
                                    <div class="small-12 columns">
                                        <img src="/static/img/games/{{ product.slug }}/img/logo-long.png" style="max-height: 60px" alt="Lottery Logo">
                                        <a href="{% url "game" product.slug %}"><div class="button radius right" style="margin-top: 15px">{% trans "Play Now" %}</div></a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="draw_entries_{{ product.slug }}">
                                <h3>{% trans "Winning numbers" %}</h3>
                                {% display_winning_numbers product.get_game %}
                            </td>
                            <td style="vertical-align: top">
                                <h3>{% trans "Jackpot" %}</h3>
                                <h2>{{ product.get_current_winning.jackpot|currency|safe }}</h2>
                            </td>
                        </tr>
                        <tr>
                            <td class="draw_entries_{{ product.slug }}">
                                <a href="{% url "game_results_game" product.slug %}">
                                    <span data-icon="&#xe007;"></span> {% trans "Click here to view the complete prize breakdown" %}
                                </a>
                            </td>
                            <td>{% trans "Last Draw Date" %}: {{ product.get_current_winning.draw_datetime|date:"l, d M Y" }}</td>
                        </tr>
                   </tbody>
                </table>
                {% endfor %}
            </div>
        </div>

        {% include "partials/sidebar.html" %}
    </section>
    <div class="clear"></div>
{% endblock %}