docs/Django/lottostar/apps/faq/urls.py
from django.conf.urls.defaults import *
from apps.faq import views

urlpatterns = patterns('faq.views',
    url(r'^admin/translate/faq/(?P<faq_id>[a-zA-Z0-9_.-]+)/$', "admin_faq_text", name="admin_faq_text"),
    url(r'^admin/translate/faqcategory/(?P<category_id>[a-zA-Z0-9_.-]+)/$', "admin_faqcategory_text", name="admin_faqcategory_text"),

    url('^$', views.FAQView.as_view(), name='faq'),
    url('^question/(?P<slug>[a-zA-Z0-9_.-]+)/$', views.FAQQuestionView.as_view(), name='faq_question'),
)

docs/Django/lottostar/local/urls.py
/home/gutembert/src/lottostar/urls.py

docs/Django/lottostar/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^',                       include('trans.urls')),
    #url(r'^',                       include('surveys.urls')),

    url(r'^admin/',                 include(admin.site.urls)),
    url(r'^admin/doc/',             include('django.contrib.admindocs.urls')),
    url(r'^admin/',                 include(admin.site.urls)),

    url(r'^admin_tools/',           include('admin_tools.urls')),
    url(r'^admin/filebrowser/',     include('filebrowser.urls')),
    url(r'^media/tinymce/',         include('tinymce.urls')),

    url(r'^faq/',                   include('faq.urls')),
    url(r'^blog/',                  include('blog.urls')),
    url(r'^',                       include('game.urls')),
    url(r'^',                       include('play.urls')),
    url(r'^',                       include('account.urls')),
    url(r'^',                       include('pages.urls')),
    url(r'^',                       include('system.urls')),
    url(r'^promotions/',            include('promotions.urls')),
    url(r'^',                       include('mobile.urls')),
    url(r'^test/',                  include('devtest.urls')),
    url(r'^',                       include('surveys.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(.*)$',            'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/static/' }),
        (r'^sites/(.*)$',             'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/sites/' }),
        (r'^admin_tools/(.*)$',       'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/static/admin_tools/'}),
        (r'^robots.txt$',             'django.views.static.serve', {'path' : "/static/robots.txt", 'document_root': settings.PROJECT_ROOT, 'show_indexes': False }),
        (r'^favicon.ico/$',           'django.views.static.serve', {'path' : "/static/favicon.ico", 'document_root': settings.PROJECT_ROOT, 'show_indexes': False }),
        (r'^media/(.*)$',             'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/media/' }),
    )

docs/Django/lottostar/apps/faq/models.py
from django.db import models
from translatable.models import TranslatableModel, get_translation_model


class FAQCategory(TranslatableModel):
    order = models.IntegerField(max_length=3, default=0)
    date_created = models.DateTimeField(auto_now=True, editable=False)
    date_modified = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        ordering = ["order"]
        verbose_name = "FAQ Category"
        verbose_name_plural = "FAQ Categories"

    def __unicode__(self):
        try:
            return self.get_translation(language="en").title
        except:
            return ""


class FAQCategoryTranslation(get_translation_model(FAQCategory, "faq_category")):
    title = models.CharField(max_length=255)

    def __unicode__(self):
        try:
            return self.model.get_translation(language="en").title
        except:
            return ""

    class Meta:
        verbose_name = "FAQ Category"
        verbose_name_plural = "FAQ Categories"



class FAQ(TranslatableModel):
    category = models.ForeignKey(FAQCategory, verbose_name="Category")
    slug = models.CharField(max_length=255)
    order = models.IntegerField(max_length=3, default=0)
    date_created = models.DateTimeField(auto_now=True, editable=False)
    date_modified = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        ordering = ["order"]

    def __unicode__(self):
        try:
            return self.get_translation(language="en").question
        except:
            return ""

    class Meta:
        verbose_name = "FAQ"
        verbose_name_plural = "FAQs"


class FAQTranslation(get_translation_model(FAQ, "faq")):
    question = models.CharField(max_length=255)
    answer = models.TextField()

    def __unicode__(self):
        try:
            return self.model.get_translation(language="en").question
        except:
            return ""

    class Meta:
        verbose_name = "FAQ"
        verbose_name_plural = "FAQs"

docs/Django/lottostar/apps/faq/views.py
from django.http import HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from apps.faq.models import FAQCategory, FAQ, FAQTranslation, FAQCategoryTranslation

def admin_faq_text(request, faq_id):
    faq = FAQ.objects.get(pk = faq_id)
    translate = FAQTranslation.objects.get_or_create(model = faq, language=request.GET.get("language", "en"))
    return HttpResponseRedirect("/admin/faq/faqtranslation/%s/" % translate[0].id)

def admin_faqcategory_text(request, category_id):
    faq = FAQCategory.objects.get(pk = category_id)
    translate = FAQCategoryTranslation.objects.get_or_create(model = faq, language=request.GET.get("language", "en"))
    return HttpResponseRedirect("/admin/faq/faqcategorytranslation/%s/" % translate[0].id)


class FAQView(ListView):
    template_name = "faq/faq.html"
    model = FAQCategory
    context_object_name = "category_list"


class FAQQuestionView(DetailView):
    template_name = "faq/faq_item.html"
    model = FAQ

docs/Django/lottostar/apps/faq/templates/faq/faq.html
{% extends "base.html" %}
{% load i18n pagination_tags %}
{% load cache %}

{% block content %}
    <section id="content" class="row">
        <div class="main-panel">
            <h1>{% trans "Frequently Asked Questions" %}</h1>
            {% cache 3600 faq %}
                <div id="faq">
                    {% for category in category_list %}
                        {% if forloop.counter0|divisibleby:"4" %}
                            <div class="row">
                        {% endif %}
                            <div class="large-4 columns">
                                <h3>{{ category.get_translation.title }}</h3>
                                <ul>
                                    {% for faq_item in category.faq_set.all %}
                                        <li><a href="{% url "faq_question" faq_item.slug %}">{{ faq_item.get_translation.question }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% if forloop.last or forloop.counter|divisibleby:"4" %}</div>{% endif %}
                    {% endfor %}
                </div>
            {% endcache %}
        </div>
        {% include "partials/sidebar.html" %}
    </section>
    <div class="clear"></div>
{% endblock %}

docs/Django/lottostar/apps/faq/templates/faq/faq_item.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    {% with faq.get_translation as faq_trans %}
        <section id="content" class="row">
            <div class="main-panel">
                <ul class="breadcrumbs">
                    <li><a href="{% url "faq" %}">{% trans "Faq" %}</a></li>
                    <li class="current"><a href=".">{{faq_trans.question}}</a></li>
                </ul>

                <h1>{{ faq_trans.question }}</h1>

                {{ faq_trans.answer|safe }} <br><br>

                <div class="clear"></div>

                <a href="{% url "faq" %}" class="button">{% trans "back" %}</a>
            </div>

            {% include "partials/sidebar.html" %}
        </section>
    {% endwith %}
{% endblock %}