docs/Django/lottostar/apps/play/urls.py
from django.conf.urls import *
from django.views.generic import TemplateView
from apps.play import views
from django.views.decorators.cache import never_cache

#checkout
urlpatterns = patterns('play.views.checkout',
    url('^checkout/$', never_cache(views.checkout.CheckoutView.as_view()), name='checkout'),
    url('^checkout/set/pay-credits/$', "paycredit", name='paycredit'),
    url('^checkout/success/$', 'checkout_success', name='checkout_complete'),
    url('^checkout/fail/$', TemplateView.as_view(template_name="play/checkout/fail.html"), name='checkout_fail'),
    url('^checkout/test/email/(?P<transaction_id>\d+)/$', 'test_email_transaction', name='test_email_transaction'),
)

#games
urlpatterns += patterns('play.views.game',
    url('^game/ticket/toggle/$', "game_ticket_toggle", name='game_ticket_toggle'),
    url('^game/ticket/clear/$', "game_ticket_clear", name='game_ticket_clear'),

    url('^game/ticket/quickpick/$', "game_ticket_quickpick", name='game_ticket_quickpick'),
    url('^game/ticket/quickpick-all/$', "game_ticket_quickpick_all", name='game_ticket_quickpick_all'),

    url('^game/ticket/addon/$', "game_ticket_addon", name='game_ticket_addon'),
    url('^game/ticket/addon-all/$', "game_ticket_addon_all", name='game_ticket_addon_all'),

    url('^game/ticket/boost/$', "game_ticket_boost", name='game_ticket_boost'),

    url('^game/set/draw/$', "game_set_draw", name='game_set_draw'),
    url('^game/set/page/$', "game_set_page", name='game_set_page'),
    url('^game/get/time/$', "game_get_time", name='game_get_time'),

    url('^game/(?P<slug>[a-zA-Z0-9_.-]+)/$', never_cache(views.game.PlayView.as_view()), kwargs={"reset_edit_session": True}, name='game'),
    url('^game/(?P<slug>[a-zA-Z0-9_.-]+)/edit/(?P<id>[a-zA-Z0-9_.-]+)/$', never_cache(views.game.EditResetView.as_view()), name='game_reset_edit'),
    url('^game/(?P<slug>[a-zA-Z0-9_.-]+)/edit/$', never_cache(views.game.PlayView.as_view()), name='game_edit'),

    url('^game/remove/basket-entry/$', "deleteEntries", name='basket_entry_delete'),
)

#transaction
urlpatterns += patterns('play.views.transactions',
    url(r'^transaction/replay-entries/delete/$', 'delete_replay_entries', {'pk': None}, name='delete_replay_entries'),
    url(r'^transaction/resend/email/(?P<transaction_id>\d+)/$', 'resend_email', name='resend-email'),
    url(r'^transaction/resend/email/successful/(?P<transaction_id>\d+)/$', 'resend_email_success',
        name='resend_email_success'),
)

docs/Django/lottostar/local/urls.py
/home/gutembert/src/lottostar/urls.py

docs/Django/lottostar/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^',                       include('trans.urls')),
    #url(r'^',                       include('surveys.urls')),

    url(r'^admin/',                 include(admin.site.urls)),
    url(r'^admin/doc/',             include('django.contrib.admindocs.urls')),
    url(r'^admin/',                 include(admin.site.urls)),

    url(r'^admin_tools/',           include('admin_tools.urls')),
    url(r'^admin/filebrowser/',     include('filebrowser.urls')),
    url(r'^media/tinymce/',         include('tinymce.urls')),

    url(r'^faq/',                   include('faq.urls')),
    url(r'^blog/',                  include('blog.urls')),
    url(r'^',                       include('game.urls')),
    url(r'^',                       include('play.urls')),
    url(r'^',                       include('account.urls')),
    url(r'^',                       include('pages.urls')),
    url(r'^',                       include('system.urls')),
    url(r'^promotions/',            include('promotions.urls')),
    url(r'^',                       include('mobile.urls')),
    url(r'^test/',                  include('devtest.urls')),
    url(r'^',                       include('surveys.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(.*)$',            'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/static/' }),
        (r'^sites/(.*)$',             'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/sites/' }),
        (r'^admin_tools/(.*)$',       'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/static/admin_tools/'}),
        (r'^robots.txt$',             'django.views.static.serve', {'path' : "/static/robots.txt", 'document_root': settings.PROJECT_ROOT, 'show_indexes': False }),
        (r'^favicon.ico/$',           'django.views.static.serve', {'path' : "/static/favicon.ico", 'document_root': settings.PROJECT_ROOT, 'show_indexes': False }),
        (r'^media/(.*)$',             'django.views.static.serve', {'document_root': settings.PROJECT_DIR + '/media/' }),
    )

docs/Django/lottostar/apps/play/models/entries.py
from django.contrib.auth.models import User
from django.db import models
from game.models import ProductGame, Product
from json_field import JSONField

class BasketEntry(models.Model):
    user = models.ForeignKey(User)

    product = models.ForeignKey(Product)
    game = models.ForeignKey(ProductGame)

    boost_value = models.IntegerField(max_length=6)
    balls = JSONField(blank=True, null=True)
    addons = JSONField(blank=True, null=True)
    draws = JSONField(blank=True, null=True)

    prize = models.FloatField(default=0, blank=True, null=True) #jackpot

    cost = models.FloatField(default=0, blank=True, null=True)
    tickets = models.IntegerField(max_length=6, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)


    class Meta:
        verbose_name = "Basket Entry"
        verbose_name_plural = "Basket Entries"
        app_label = "play"

docs/Django/lottostar/apps/play/models/result_email_user.py
from django.contrib.auth.models import User
from django.db import models
from game.models import Event
from play.models import SystemEmail

class ResultEmailUser(models.Model):
    user = models.ForeignKey(User)
    event = models.ForeignKey(Event)
    system_email = models.ForeignKey(SystemEmail, null=True, blank=True)

    has_sent = models.BooleanField(default=False, db_index=True)
    has_failed = models.BooleanField(default=False, db_index=True)

    class Meta:
        app_label = "play"

docs/Django/lottostar/apps/play/forms/game.py
from django import forms
import settings
from apps.game.models import Product


class ProcessForm(forms.Form):
    total_cost = forms.CharField(widget=forms.HiddenInput)


class CheckoutForm(forms.Form):
    buy_play_credits = forms.FloatField(widget=forms.TextInput(attrs={"onkeypress": "return numbersonly(event)"}), required=False, initial=10.00)

    def clean_buy_play_credits(self):
        buy_play_credits = self.cleaned_data['buy_play_credits']
        play_with_credits = self.data.get('play_with_credits', False)
        user = self.data.get('user', 'AnonymousUser')
        if user != 'AnonymousUser' and play_with_credits:
            minimum_play_credits = getattr(settings, 'MINIMUM_PLAY_CREDITS', None)
            if buy_play_credits < minimum_play_credits:
                raise forms.ValidationError('Minimum of {0} is allowed'.format(minimum_play_credits))
        return buy_play_credits


class PlayCreditForm(forms.Form):
    buy_play_credits = forms.FloatField(widget=forms.TextInput(attrs={"onkeypress": "return numbersonly(event)"}), required=False, initial=10.00)


class GameOverviewForm(forms.Form):
    games = forms.ModelMultipleChoiceField(queryset=Product.objects.all(), widget=forms.CheckboxSelectMultiple(), required=False)
    from_date = forms.DateField(input_formats=("%d-%m-%Y",), required=False)
    to_date = forms.DateField(input_formats=("%d-%m-%Y",), required=False)


class ResendTransactionEmailForm(forms.Form):
    to = forms.EmailField()

docs/Django/lottostar/apps/play/views/checkout.py
from __future__ import division
import itertools
import json
from datetime import timedelta, datetime
from dateutil.relativedelta import relativedelta
from django.contrib import messages
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.template import RequestContext
from django.views.generic import  FormView
from django.shortcuts import get_object_or_404, render_to_response
from apps.account.models import UserProfile, UserWallet, Restriction
from apps.game.models import Event, Game, ProductGame
from play.forms.game import CheckoutForm, PlayCreditForm
from play.functions import pickle, get_session_details, get_final_cost, get_final_cost_context
from play.models.transaction import Ticket, Transaction, Entry, TransactionVoucher, Deck
from play.models.entries import BasketEntry, Product
from play.utils import *
from django.views.generic import TemplateView
from promotions.functions import get_offer_helper, clean_checkout_session
from promotions.models import Offer, OfferCustomer
from django.db.models import F
from system.models.log import Log
from utils.mailer import SendMail
from play.models import ReplayEntries
from django.db.models import Sum
import settings

from django.contrib.auth.views import logout



class CheckoutView(FormView):
    form_class = CheckoutForm
    template_name = "play/checkout/checkout.html"
    game_list = {}
    basket_list = []
    total_cost = 0
    total_entries = 0
    total_entries_per_draw = 0
    product_list = []
    in_product_list = []
    buy_play_credits = 0
    play_credits = 0
    discount = 0
    vouchers = 0
    payment_due = 0
    voucher_list = []
    restriction = False
    limit_message = ""
    limit = {"period": "monthly", "entries_left": 0}

    def check_transaction_limit(self, type):
        if self.request.user.is_authenticated():
            daily_limit = datetime.now() - timedelta(hours=24)
            weekly_limit = datetime.now() - timedelta(weeks=1)
            monthly_limit = datetime.now() - relativedelta(months=1)

            daily_filter = {'created_at__gte': daily_limit}
            weekly_filter = {'created_at__gte': weekly_limit}
            monthly_filter = {'created_at__gte': monthly_limit}

            transaction_type = {
                'deposit': Transaction.TRANSACTION_TYPE_CHOICES.purchase_play_credit,
                'entry': Transaction.TRANSACTION_TYPE_CHOICES.entry_purchased
            }
            transaction_limit = Restriction.get_latest_limit(self.request.user, type)
            if not transaction_limit or transaction_limit.value == 0:
                return None

            transaction_list = Transaction.objects.filter(
                user=self.request.user, transaction_type=transaction_type[type])
            if transaction_limit.period == "daily":
                transaction_list = transaction_list.filter(**daily_filter)
            if transaction_limit.period == "weekly":
                transaction_list = transaction_list.filter(**weekly_filter)
            if transaction_limit.period == "monthly":
                transaction_list = transaction_list.filter(**monthly_filter)
            if type == 'deposit':
                deposit_total = transaction_list.aggregate(Sum('total_paid'))
                deposit_limit = transaction_limit.value
                if deposit_total['total_paid__sum']:
                    deposit_limit = transaction_limit.value - deposit_total['total_paid__sum']
                return deposit_limit
            else:
                total_trans_entries = Entry.objects.filter(
                    ticket__transaction__id__in=transaction_list.values_list('id', flat=True)).count()
                entries_count = total_trans_entries + self.total_entries
                if entries_count > transaction_limit.value:
                    amount_over = entries_count - transaction_limit.value
                    self.limit["amount_over"] = amount_over
                    self.limit_message = _("Your entry limit of {0} has been exceeded. Please remove or update your\
                        game(s) to proceed.".format(self.limit["period"]))
                    return self.limit_message
            return None
        return None

    def fetch_basket(self):
        is_authenticated = self.request.user.is_authenticated()
        game_list = []
        delete_que = []

        self.basket_list = self.request.session.get("basket", {})

        for x, item in enumerate(self.basket_list):
            basket_item = self.basket_list[item]
            session = {"basket": {basket_item["id"]: basket_item}}
            item_args = get_session_details(basket_item["product_slug"], session, "basket", basket_item["id"])
            if is_authenticated:
                bmodel = BasketEntry(
                    user=self.request.user, product=item_args["product"], game=item_args["game"],
                    boost_value=item_args["boost_value"], balls=json.dumps(item_args["tickets"]),
                    addons=json.dumps(item_args["addons"]), draws=json.dumps(item_args["draws"]),
                    prize=item_args["jackpot_float"], cost=item_args["total_cost"],
                    tickets=item_args["total_entries_per_draw"],
                )
                bmodel.save()
                delete_que.append(item)
            else:
                game_list.append(item_args)

        if is_authenticated:
            for x, item in enumerate(delete_que):
                del self.basket_list[item]
            self.request.session["basket"] = self.basket_list
            basket = BasketEntry.objects.filter(user=self.request.user)
        else:
            basket = self.request.session.get("basket", {})

        # basket entry is a deck with tickets
        self.basket_list = []
        for item in basket:
            if is_authenticated:
                session = {"model": {item.id : {
                    "id": item.id,
                    "product": item.product,
                    "product_slug": item.product.slug,
                    "boost_value" : item.boost_value,
                    "tickets": pickle(item.balls),
                    "addons" : pickle(item.addons),
                    "draws": pickle(item.draws),
                }}}
                args = get_session_details(item.product.slug, session, "model", item.id)
            else:
                bitem = basket[item]
                session = {"basket": {int(bitem["id"]) : {
                    "id": int(bitem["id"]),
                    "product_slug": bitem["product_slug"],
                    "boost_value" : bitem["boost_value"],
                    "tickets": bitem["tickets"],
                    "addons" : bitem["addons"],
                    "draws": bitem["draws"],
                }}}
                args = get_session_details(bitem["product_slug"], session, "basket", int(bitem["id"]))

            self.total_entries_per_draw += int(args["total_entries_per_draw"])
            self.total_entries += int(args["total_entries"])
            self.basket_list.append(args)

        self.product_list = []
        self.in_product_list = []
        for item in self.basket_list:
            total_cost = 0

            for loop_item in self.basket_list:
                if item["product"] == loop_item["product"]:
                    total_cost += float(loop_item["total_cost"])

            if not item["product"] in self.in_product_list:
                self.in_product_list.append(item["product"])
                start_event = Event.objects.get(pk=item["draws"]["start_event"])
                draw_days = item['draws']['days'].title().replace('-', ', ')
                self.product_list.append(
                    {"product": item["product"], "total_cost": total_cost, "start_on": start_event.draw_datetime,
                     "draw_days": draw_days, "total_entries": item['total_entries']})


    def get(self, request, *args, **kwargs):
        self.fetch_basket()
        return super(CheckoutView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.fetch_basket()
        return super(CheckoutView, self).post(request, *args, **kwargs)

    def get_initial(self):
        initial = super(CheckoutView, self).get_initial()
        initial.update(get_final_cost_context(self.request, self.basket_list, self.product_list, self.total_entries, self.total_entries_per_draw))
        return initial

    def form_valid(self, form):
        if self.request.user.is_authenticated():
            if not self.check_transaction_limit('entry'):
                objects = get_final_cost_context(self.request, self.basket_list, self.product_list, self.total_entries, self.total_entries_per_draw)

                # add the replayed entries to the total cost of the transaction
                # replay_entries = ReplayEntries.objects.filter(user=self.request.user, is_processed=False)
                # replay_entries_total = replay_entries.aggregate(Sum('price'))
                # if replay_entries_total['price__sum']:
                #     objects["total_cost"] += replay_entries_total['price__sum']

                #delete transaction, buy_play_credits on session
                try:
                    del self.request.session['transaction']
                    del self.request.session['deposit']
                except KeyError:
                    pass

                # safe guard to ensure that the user does not exceed deposit limit
                if form.cleaned_data["buy_play_credits"]:
                    buy_play_credits = float(form.cleaned_data["buy_play_credits"])
                else:
                    buy_play_credits = 0.00
                deposit_limit = self.check_transaction_limit('deposit')
                # if the amount deposited by the user exceeds the deposit limit clear it

docs/Django/lottostar/apps/play/templates/play/checkout/checkout.html
{% extends "base.html" %}

{% load i18n game_tags webdesign humanize %}
{% load promotions_tags %}

{% block js %}
    <script type="text/javascript" src="/static/js/checkout.js"></script>
    <script>
    $(document).ready(function(){
        /*
        * check if the inserted deposit amount does not exceed the user's deposit limit if so display error message
        * and clear the deposit input field.
        * */
        // the maximum value a user can deposit
        var deposit_limit = '{{ deposit_limit }}';
        deposit_limit = parseInt(deposit_limit)
        $("#id_buy_play_credits").val('0.00')
        var initial_deposit_value = parseInt($("#id_buy_play_credits").val())
         $("#id_buy_play_credits").on('keyup', function(){
            var deposit_value = parseInt($(this).val())
            if(deposit_value > deposit_limit){
                alert('Deposit limit exceeded. Max allowed deposit is: ' + deposit_limit)
                $(this).val('0.00')
            }
        });
    })
</script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="/static/css/site.css"/>
{% endblock %}

{% block content %}
    <checkout>
        <div id="confirm_message" style="display: none;">{% trans "Click OK if you want to delete this from you basket" %}</div>
        <div id="csrf_token_id" style="display: none;">{{csrf_token}}</div>

        <section id="content" class="row">
            <div class="main-panel" id="checkout">
                <h1>{% trans "Checkout" %}
                    <br/>
                    <small>
                        {% if game_list %}
                            {% trans "Please review your order" %}
                        {% else %}
                            {% trans "Please choose one of the games below and play:" %}
                        {% endif %}
                    </small>
                </h1>

                {% if form.errors %}
                    <div class="alert alert-error">
                        <p>{{ form.errors }}</p>
                    </div>

                {% endif %} 

                {% if transaction_limit %}
                    <div class="row large-12">
                        <div class="alert alert-error">
                            <p><strong>{{ transaction_limit }}</strong></p>
                        </div>
                    </div>
                {% endif %}
                {% comment %}
                <div style="margin-bottom: 30px;">
                    <a href="{% url 'delete_replay_entries' %}" class="button radius" style="margin-right: 10px;">Delete all replayed entries</a>
                    <a href="{% url 'delete_replay_entries' %}" class="button radius">Edit replayed entries</a>
                </div>
                {% endcomment %}
                {% if game_list %}
                    <div class="row">
                        <div class="large-12 columns">
                            <table class="entries">
                                <thead>
                                    <tr>
                                        <td width="155" class="heading">{% trans "Product" %}</td>
                                        <td width="350">{% trans "Duration" %}</td>
                                        <td width="335">{% trans "Breakdown" %}</td>
                                        <td width="100">{% trans "Total" %}</td>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for game in game_list %}
                                <tr class="game_basket_entry game_identifier_{{game.product.get_game.id}}" id="game_basket_entry_{{ game.id }}">
                                    <td style="vertical-align: top" id="">
                                       <a href="/game/{{ game.product.slug }}/edit/{{ game.id }}/"><img style="padding-top: 10px" src="/static/img/games/{{ game.product.slug }}/img/logo.png" width="100%"></a>
                                    </td>

                                    <td style="vertical-align: top" id="">
                                        <div class="row collapse">
                                            <div class="small-10 columns">
                                                <ul>
                                                    <li><h3><a href="/game/{{ game.product.slug }}/edit/{{ game.id }}/">{{ game.product.name }}</a></h3></li>
                                                    <li>
                                                        <strong>{% trans "Starting Date" %}:</strong> {{ game.draws|get_dict:"start_event"|get_draw_datetime|date:"d F Y" }}<br>
                                                        <strong>{% trans "Weeks" %}:</strong> {{ game.draws|get_dict:"duration" }}<br>
                                                        {% if game.draws|get_dict:"duration" == 1 and not "&" in game.draws|get_dict:"days"|format_days %}
                                                            <strong>{% trans "Play Days" %}:</strong>
                                                            {{ game.draws|get_dict:"days"|format_days }}.
                                                        {% else %}
                                                            <strong>{% trans "Play Days" %}:</strong>
                                                            {% if game.draws|get_dict:"duration" > 1 %} {{ game.draws|get_dict:"duration" }} {% trans "weeks, for " %} {% endif %}
                                                            {% if "&" in game.draws|get_dict:"days"|format_days %}{% else %}{% trans "only " %}{% endif %}{{ game.draws|get_dict:"days"|format_days }}.
                                                        {% endif %}
                                                    </li>
                                                </ul>
                                            </div>
                                            <div class="small-2 columns">
                                                <div class="edit">
                                                   <a href="#" onclick='removeEntry("{{ game.product.slug }}", {{game.id}}, {{game.product.get_game.id}}); return false;'><span data-icon="&#x51;" title=" {% trans "Remove" %}"></span></a>
                                                   <a href="/game/{{ game.product.slug }}/edit/{{ game.id }}/"><span data-icon="&#x3c;" title=" {% trans "Edit" %}"></span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </td>

                                    <td style="vertical-align: top">
                                        <ul>
                                            <li>
                                                <strong>{% trans "Enties per draw" %}:</strong> {{ game.total_entries_per_draw }}
                                            </li>
                                            <li>
                                                <strong>{% trans "Total Entries" %} :</strong> {{ game.total_entries }}
                                            </li>
                                            <li>
                                                {% if game.boost_value %}
                                                    <strong>{% trans "Boost" %}: </strong> {{ game.boost_value }}
                                                {% else %}
                                                    {% trans "Standard Game" %}
                                                {% endif %}
                                            </li>
                                            <li><strong>{% trans "Jackpot" %}:</strong> &euro; {{ game.jackpot }} </li>
                                        </ul>

                                    </td>
                                    <td style="vertical-align: top">
                                        &euro; {{ game.total_cost|floatformat:2|intcomma }}
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% if voucher_list and total_vouchers > 0 %}
                            <div class="large-12 columns" id="basket_vouchers">
                                <h2>{% trans "Your Vouchers" %}</h2>
                                <table class="account large-12">
                                    <thead>
                                    <tr>
                                        <td>{% trans "Products" %}</td>
                                        <td>{% trans "Vouchers" %}</td>
                                        <td>{% trans "Discounted" %}</td>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for voucher in voucher_list %}
                                        {% if  voucher.vouchers > 0 %}
                                            <tr class="game_basket_vouchers" id="game_basket_entry_vouchers_{{ voucher.product.get_game.id }}">
                                                <td width="20%"><center><img src="/static/img/games/{{ voucher.product.slug }}/img/logo.png" width="90%"></center></td>
                                                <td width="55%">
{#                                                    <strong>{{ voucher.product.name }}</strong> <br/>#}
                                                    <br/>
                                                    {% trans "Used" %}: {{ voucher.vouchers }} {% trans "of" %} {{ voucher.of_vouchers }} <br/>
{#                                                    {% trans "Single Voucher Cost" %}: &euro; {{ voucher.voucher_cost|floatformat:2 }} <br/>#}
                                                </td>
                                                <td width="35%">
{#                                                    {% trans "Total Game Cost" %}: &euro; {{ voucher.game_cost|floatformat:2 }} <br>#}
{#                                                    {% trans "Total Voucher Cost" %}:#} &euro; {{ voucher.used_cost|floatformat:2 }}
{#                                                    <br/>#}
{#                                                    {% trans "Sub Total" %}: &euro; {{ voucher.total_cost|floatformat:2 }}#}
                                                </td>
                                            </tr>
                                        {% endif %}
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        {% endif %}


                        <form action="." class="custom" method="post">
                            {% csrf_token %}
                            {# field that allows us to get the user's details on the form #}
                            <input type="hidden" name="user" value="{{ user }}">
                            <input type="hidden" name="play_with_credits" value="{{ play_with_credits }}">
                            {% if play_with_credits and payment_due %}
                                <div class="large-12 columns">
                                    <table class="account">
                                        <tbody>
                                            <tr>
                                                <td width="757">{% trans "Buy play credits" %} ( {% trans "minimun amount" %}: &euro; {{ minimum_play_credits }} ) </td>
                                                <td width="233">{{ form.buy_play_credits }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            {% endif %}

                            <div class="large-6 columns"></div>

                            <div class="large-6 columns">
                                <div id="final_cost">
                                    {% include "play/partials/checkout_final_prices.html" %}
                                </div>
                                {% if not transaction_limit %}
                                    <button type="submit" class="button radius expand greenbtn" id="btnCheckout">{% trans "complete purchase" %}</button>
                                {% endif %}
                            </div>
                        </form>

                    <div class="large-5 columns">
                        {% get_products_promotion_offers product_list %}
                    </div>
                </div>
                {% else %}
                    {% include "play/partials/game_selectors.html" %}
                    <div class="row">
                        <div class="large-12 columns">
                            <h2>{{ config.blank_checkout.get_translation.title }}</h2>
                            <p>
                                {{ config.blank_checkout.get_translation.content|safe }}
                            </p>
                        </div>
                    </div>
                {% endif %}
            </div>
            {% include "partials/sidebar.html" %}
        </section>
    </checkout>
    <div class="clear"></div>

{% endblock %}